### ISSUE TITLE
[BUG] Please add a speaking title

### ISSUE THREAD

**Issue by liayn** [TYPO3-Solr/ext-solr#2640]
Accessing the Reports module in BE ends with

```
ArgumentCountError
Too few arguments to function TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController::getPageAndRootlineWithDomain(), 1 passed in /var/www/html/typo3conf/ext/solr/Classes/FrontendEnvironment/Tsfe.php on line 105 and exactly 2 expected
```

**To Reproduce**
Try to access the Reports module in the Backend.

**Expected behavior**
No error message.

**Used versions (please complete the following information):**
 - TYPO3 Version: 10.4.4
 - EXT:solr Version: 11.0.1
 - PHP Version: 7.4.6

`TSFE::getPageAndRootlineWithDomain($rootPageId, ServerRequestInterface $request)`` 
is called in solr/Classes/FrontendEnvironment/Tsfe.php line 105 with
`$GLOBALS['TSFE']->getPageAndRootlineWithDomain($pageId);`
which is obviously wrong.

**Comment by georgringer** [comment]
Thanks for the report, just some additional info. The method `getPageAndRootlineWithDomain` is flagged as internal and changed in june with following commit https://github.com/TYPO3/TYPO3.CMS/commit/15e23367c41ecd899db4fbbe3e6c41c23598e282#diff-0df58cdf10f2b3f92e4625bd614e611fR996

**Comment by georgringer** [comment]
Changing the line in `Tsfe.php` to 
```php
$request = \TYPO3\CMS\Core\Http\ServerRequestFactory::fromGlobals();
$GLOBALS['TSFE']->getPageAndRootlineWithDomain($pageId, $request);
```

makes it work again

**Comment by timohund** [comment]
@georgringer @liayn Thanks for the report and additional information. We will provide a fix for that.

We should check that our fix release still works with TYPO3 versions below 10.4.4
